# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Informatica – L31

theme:
  name: material

  font:
    text: Montserrat
    code: Fira Code

  language: it

  # icon:
  #   logo: bootstrap/envelope-paper

  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      accent: blue
      toggle:
        icon: material/weather-night
        name: Passa alla modalità chiara

    # Palette toggle for light mode
    - scheme: default
      primary: green
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Passa alla modalità scura

  features:
    - navigation.instant # basically behave like a single page app
    - navigation.tracking # URL gets updated when highlighting anchor
    - navigation.tabs # tabs rendered below header
    - navigation.tabs.sticky # tabs are sticky
    - navigation.sections # sections are rendered as groups in the navigation
    - toc.follow #
    # - toc.integrate
    - navigation.top


  # extra:
  # consent:
  #   title: Cookie consent
  #   description: >-
  #     We use cookies to recognize your repeated visits and preferences, as well
  #     as to measure the effectiveness of our documentation and whether users
  #     find what they're searching for. With your consent, you're helping us to
  #     make our documentation better.

  # actions:
  #   - accept
  #   - manage
  #   - reject

