---
name: ci
run-name: Deploy documentation

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - name: Cache stuff
        uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Upgrade python
        run: >-
          python -m pip install --upgrade pip

      - name: Install mkdocs-material and dependencies
        run: >-
          pip install mkdocs-material
          pip install mkdocs-git-revision-date-localized-plugin \
              pillow \
              cairosvg \
              mkdocs-glightbox

      - name: Deploy
        run: mkdocs gh-deploy --force
