name: Changelog generator
run-name: ${{ github.actor }} is generating changelog 📝
on: [push]

jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
        with:
          fetch-depth: 0

      - name: git-cliff - Changelog Generator
        uses: orhun/git-cliff-action@v1.1.7
        id: git-cliff
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add CHANGELOG.md
          git commit -m "feat(auto) :gear: generate changelog"
          git push

      - name: Print the changelog
        run: cat "${{ steps.git-cliff.outputs.changelog }}"
